# **SCT_DA_2**

## **1. Import Libraries**

In [62]:
import pandas as pd
import numpy as np

## **2. Import Data**

In [63]:
df = pd.read_csv(r'C:\Users\sujal\Downloads\superstore.csv')

## **3. Preview Dataset**

In [64]:
df.head(10)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40
5,Office Supplies,Los Angeles,United States,JF-154904,Jeremy Farry,0.0,US,1,2011-10-19 00:00:00.000,CA-2011-117317,...,13,Consumer,2011-10-19 00:00:00.000,Same Day,2.39,California,Paper,2011,North America,43
6,Office Supplies,Los Angeles,United States,WB-218504,William Brown,0.0,US,1,2011-11-04 00:00:00.000,CA-2011-125829,...,19,Consumer,2011-11-11 00:00:00.000,Standard Class,1.15,California,Paper,2011,North America,45
7,Office Supplies,Los Angeles,United States,JA-159704,Joseph Airdo,0.0,US,1,2011-11-12 00:00:00.000,CA-2011-151295,...,12,Consumer,2011-11-16 00:00:00.000,Standard Class,0.92,California,Paper,2011,North America,46
8,Office Supplies,Los Angeles,United States,SP-209204,Susan Pistek,0.0,US,1,2011-11-22 00:00:00.000,CA-2011-135090,...,54,Consumer,2011-11-26 00:00:00.000,Standard Class,6.98,California,Paper,2011,North America,48
9,Office Supplies,Los Angeles,United States,RL-196154,Rob Lucas,0.0,US,1,2011-12-05 00:00:00.000,CA-2011-133830,...,49,Consumer,2011-12-10 00:00:00.000,Standard Class,1.99,California,Paper,2011,North America,50

In [65]:
df.shape

(51290, 27)

In [66]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [67]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [68]:
df.dropna(inplace=True)

In [69]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df.drop(['记录数', 'Market2', 'Customer.ID'], axis=1, inplace=True)

In [72]:
df.head()

,Category,City,Country,Customer.Name,Discount,Market,Order.Date,Order.ID,Order.Priority,Product.ID,...,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,weeknum
0,Office Supplies,Los Angeles,United States,Lycoris Saunders,0.0,US,2011-01-07 00:00:00.000,CA-2011-130813,High,OFF-PA-10002005,...,36624,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,2
1,Office Supplies,Los Angeles,United States,Mark Van Huff,0.0,US,2011-01-21 00:00:00.000,CA-2011-148614,Medium,OFF-PA-10002893,...,37033,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,4
2,Office Supplies,Los Angeles,United States,Chad Sievert,0.0,US,2011-08-05 00:00:00.000,CA-2011-118962,Medium,OFF-PA-10000659,...,31468,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,32
3,Office Supplies,Los Angeles,United States,Chad Sievert,0.0,US,2011-08-05 00:00:00.000,CA-2011-118962,Medium,OFF-PA-10001144,...,31469,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,32
4,Office Supplies,Los Angeles,United States,Arthur Prichep,0.0,US,2011-09-29 00:00:00.000,CA-2011-146969,High,OFF-PA-10002105,...,32440,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,40

In [73]:
df.rename(columns={'Sub.Category': 'Sub_Category','Order.Date': 'Order_Date','Ship.Date': 'Ship_Date'}, inplace=True)

In [74]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.Name', 'Discount', 'Market',
       'Order_Date', 'Order.ID', 'Order.Priority', 'Product.ID',
       'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID', 'Sales',
       'Segment', 'Ship_Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub_Category', 'Year', 'weeknum'],
      dtype='object')

In [75]:
df.head()

,Category,City,Country,Customer.Name,Discount,Market,Order_Date,Order.ID,Order.Priority,Product.ID,...,Row.ID,Sales,Segment,Ship_Date,Ship.Mode,Shipping.Cost,State,Sub_Category,Year,weeknum
0,Office Supplies,Los Angeles,United States,Lycoris Saunders,0.0,US,2011-01-07 00:00:00.000,CA-2011-130813,High,OFF-PA-10002005,...,36624,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,2
1,Office Supplies,Los Angeles,United States,Mark Van Huff,0.0,US,2011-01-21 00:00:00.000,CA-2011-148614,Medium,OFF-PA-10002893,...,37033,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,4
2,Office Supplies,Los Angeles,United States,Chad Sievert,0.0,US,2011-08-05 00:00:00.000,CA-2011-118962,Medium,OFF-PA-10000659,...,31468,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,32
3,Office Supplies,Los Angeles,United States,Chad Sievert,0.0,US,2011-08-05 00:00:00.000,CA-2011-118962,Medium,OFF-PA-10001144,...,31469,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,32
4,Office Supplies,Los Angeles,United States,Arthur Prichep,0.0,US,2011-09-29 00:00:00.000,CA-2011-146969,High,OFF-PA-10002105,...,32440,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,40

## **4.Check Data Types**

In [76]:
df.dtypes

Category           object
City               object
Country            object
Customer.Name      object
Discount          float64
Market             object
Order_Date         object
Order.ID           object
Order.Priority     object
Product.ID         object
Product.Name       object
Profit            float64
Quantity            int64
Region             object
Row.ID              int64
Sales               int64
Segment            object
Ship_Date          object
Ship.Mode          object
Shipping.Cost     float64
State              object
Sub_Category       object
Year                int64
weeknum             int64
dtype: object

In [77]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'])

In [78]:
df['Category'] = df['Category'].astype('category')
df['Segment'] = df['Segment'].astype('category')
df['Region'] = df['Region'].astype('category')
df['Sub_Category'] = df['Sub_Category'].astype('category')
df['Ship.Mode'] = df['Ship.Mode'].astype('category')

In [79]:
df.dtypes

Category                category
City                      object
Country                   object
Customer.Name             object
Discount                 float64
Market                    object
Order_Date        datetime64[ns]
Order.ID                  object
Order.Priority            object
Product.ID                object
Product.Name              object
Profit                   float64
Quantity                   int64
Region                  category
Row.ID                     int64
Sales                      int64
Segment                 category
Ship_Date         datetime64[ns]
Ship.Mode               category
Shipping.Cost            float64
State                     object
Sub_Category            category
Year                       int64
weeknum                    int64
dtype: object

In [83]:
df.to_csv('Cleaned_Global_Superstore.csv', index=False)